group: travis_latest
language: php

env:
  - TEST_SUITE=unit
  - TEST_SUITE=functional
  - TEST_SUITE=efficiency
php:
  - 7.3
  - 7.2
  - 7.1
  - nightly

matrix:
  include:
    - php: 7.1
      env: lowest=1
    - php: 7.2
      env: csfixer=1
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer

install:
  - phpenv config-rm xdebug.ini || true;
  - |
    if [ "$csfixer" != "1" ]; then
      composer remove --dev friendsofphp/php-cs-fixer;
    fi;
  - |
    if [ "$lowest" = "1" ]; then
      composer update --prefer-lowest --prefer-stable;
    else
      composer update;
    fi;

script:
  - |
    if [ "$csfixer" = "1" ]; then
      vendor/bin/php-cs-fixer fix --verbose --dry-run --diff --diff-format=udiff --allow-risky=yes;
    fi;
  - |
    if [ "${TEST_SUITE}" = "unit" ]; then
      php vendor/bin/phpunit --exclude-group efficiency;
    elif [ "${TEST_SUITE}" = "efficiency" ]; then
      php vendor/bin/phpunit --group efficiency;
    elif [ "${TEST_SUITE}" = "functional" ]; then
      php vendor/bin/behat --strict;
    fi;
